Create user
Grom013/twitter pull request #98
Opened 2024-05-02 08:51 UTC by Grom013

добавил метод для отправки нового пользователя на сервер

2024-05-05 14:17 UTC, burtovoy requested changes

2024-05-05 14:17 UTC, burtovoy commented on tests/calc.test.js
> +
Это точно относится к этой задаче? )

2024-05-05 21:16 UTC, Grom013 commented
Eslint добавил отступы после каждого теста

2024-05-05 21:17 UTC, Grom013 commented on tests/calc.test.js
> +
Eslint добавил пустую строчку после каждого теста

2024-05-06 11:05 UTC, burtovoy commented on tests/calc.test.js
> +
Все что не относится к текущей задаче нужно делать через отдельный PR

2024-05-06 11:45 UTC, Grom013 commented on tests/calc.test.js
> +
Нужно теперь отменить этот PR, и заново сделать все?

2024-05-06 11:47 UTC, burtovoy commented on tests/calc.test.js
> +
Да

2024-05-07 13:49 UTC, closed without merging